/*
EJEMPLOS
~/compile_farm/woody/var/farmas/fuentes/dbfapi CREARDRIVER driv001
~/compile_farm/woody/var/farmas/fuentes/dbfapi CARGARDRIVER driv001 2 3 4 5 CREATE
~/compile_farm/woody/var/farmas/fuentes/dbfapi CARGARDRIVER driv001 2 DDLDML C DDL GO 1
~/compile_farm/woody/var/farmas/fuentes/dbfapi CARGARDRIVER driv001 2 ENTITY C TABLE GO 1
*/
DO GX_INIT
PARA TABLA0, TABLA1, TABLA2, PNAME3, PTYPE4, PVALUE5, PCREATE6, PGO7, PGORN8

PRIVATE CAMPOSSTRUCT
PRIVATE PASO
PRIVATE PAUSERES
PRIVATE PVARNAME
PRIVATE REFBY
PRIVATE TERMINAR
PRIVATE VGORN
PRIVATE VNAME
PRIVATE VPAUSERES
PRIVATE VTABLA
PRIVATE VTABLENAME
PRIVATE VVALUE
PRIVATE VAREA
PRIVATE REFBYNROLIN

DO CASE
CASE TABLA0="CREARDRIVER"
     SELECT 1
     CAMPOSSTRUCT := {}
     AADD(CAMPOSSTRUCT, { "LINEREADY" , "C" , 1, 0 } )
     AADD(CAMPOSSTRUCT, { "NROLIN" , "N" , 18 , 0 } )
     AADD(CAMPOSSTRUCT, { "NROLINNEXT" , "N" , 18 , 0 } )
     AADD(CAMPOSSTRUCT, { "DDLDML" , "C" , 3 , 0 } )
     AADD(CAMPOSSTRUCT, { "ENTITY" , "C" , 15 , 0 } )
     AADD(CAMPOSSTRUCT, { "OP" , "C" , 15 , 0 } )
     AADD(CAMPOSSTRUCT, { "DONE" , "C" , 1 , 0 } )
     AADD(CAMPOSSTRUCT, { "NAME" , "C" , 15 , 0 } )
     AADD(CAMPOSSTRUCT, { "TYPE" , "C" , 15 , 0 } )
     AADD(CAMPOSSTRUCT, { "VALUEC" , "C" , 255 , 0 } )
     AADD(CAMPOSSTRUCT, { "VALUEC2" , "C" , 255 , 0 } )
     AADD(CAMPOSSTRUCT, { "VALUED" , "D" , 8 , 0 } )
     AADD(CAMPOSSTRUCT, { "VALUEN" , "N" , 18 , 5 } )
     AADD(CAMPOSSTRUCT, { "VALUEN2" , "N" , 18 , 5 } )
     AADD(CAMPOSSTRUCT, { "GORN" , "N" , 18 , 0 } )
     
     DBCREATE( (TABLA1) , CAMPOSSTRUCT )
     RETURN

CASE TABLA0="CARGARDRIVER"
     SELECT 1
     USE &TABLA1
     DO CASE
     	CASE PCREATE6="CREATE"
	     APPEND BLANK
     	CASE PGO7="GO"
	     GO VAL(PGORN8)
     ENDCASE
     DO CASE
     	CASE PTYPE4="C"
	     REPLACE &PNAME3 WITH PVALUE5
     	CASE PTYPE4="N"
	     REPLACE &PNAME3 WITH VAL(PVALUE5)
     ENDCASE
     RETURN
ENDCASE
SELECT 1
USE (TABLA0) SHARED
PASO=1
GO (PASO)
TERMINAR=.F.
REFBY=0
VAREA=2
WHILE .NOT. TERMINAR .AND. .NOT. EOF()
DO WHILE (LINEREADY!="T")
  PAUSERES=SLEEP( 0.5 )
ENDDO
DO CASE
CASE DDLDML="DML" .AND. ENTITY="FIELD" .AND. OP="C"
     IF REFBY = 0
        APPEND BLANK
     ENDIF
     REPLACE &NOMBRE WITH VALOR
CASE DDLDML="DML" .AND. ENTITY="FIELD" .AND. OP="R"
     VNAME=NAME
     SELECT (VAREA)
     VVALUE=&(VNAME)
     SELECT 1
     DO CASE
        CASE TYPE="C"
	     REPLACE VALUEC WITH VVALUE
        CASE TYPE="D"
	     REPLACE VALUED WITH VVALUE
        CASE TYPE="N"
	     REPLACE VALUEN WITH VVALUE
     ENDCASE
     REPLACE DONE WITH "T"
     COMMIT
CASE DDLDML="DML" .AND. ENTITY="FIELD" .AND. OP="U"
     VNAME=NAME
     DO CASE
        CASE TYPE="C"
           VVALUE=VALUEC
        CASE TYPE="D"
           VVALUE=VALUED
        CASE TYPE="N"
           VVALUE=VALUEN
	CASE TYPE="P"
           VVALUE=&PVARNAME
     ENDCASE
     SELECT (VAREA)
     REPLACE &VNAME WITH VVALUE
CASE DDLDML="DML" .AND. ENTITY="FIELD" .AND. OP="D"
     SELECT (VAREA)
     DELETE
CASE DDLDML="DDL" .AND. ENTITY="INDEX" .AND. OP="SET"
     VVALUE=VALUEC
     SELECT (VAREA)
     SET INDEX TO &VVALUE
CASE DDLDML="DDL" .AND. ENTITY="INDEX" .AND. OP="CREATE"
     SELECT (VAREA)
     INDEX ON &(VALUEC) TO &(VALUEC2)
CASE DDLDML="DDL" .AND. ENTITY="INDEX" .AND. OP="REINDEX"
     SELECT (VAREA)
     REINDEX 
CASE DDLDML="DDL" .AND. ENTITY="INDEX" .AND. OP="DELETE"
CASE DDLDML="DDL" .AND. ENTITY="ORDER" .AND. OP="SET"
CASE DDLDML="DDL" .AND. ENTITY="ORDER" .AND. OP="UNSET"
CASE DDLDML="DDL" .AND. ENTITY="ORDER" .AND. OP="GET"
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="SELECTAREA"
     VAREA=VALUEN
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="SELECTTABLE"
     VAREA=VALUEC
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="USEEXCLUSIVE"
     VTABLA=NAME
     SELECT (VAREA)
     USE &VTABLA
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="USESHARED"
     VTABLA=NAME
     SELECT (VAREA)
     USE &VTABLA SHARED
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="GO"
     VGORN=GORN
     SELECT (VAREA)
     GO (VGORN)
     PASO=VGORN
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="SEEK"
     DO CASE
         CASE TYPE="C"
              VVALUE=VALUEC
         CASE TYPE="D"
              VVALUE=VALUED
         CASE TYPE="N"
              VVALUE=VALUEN
     ENDCASE
     SELECT (VAREA)
     SEEK VVALUE
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="SEARCH"
     DO CASE
         CASE TYPE="C"
              VVALUE=VALUEC
         CASE TYPE="D"
              VVALUE=VALUED
         CASE TYPE="N"
              VVALUE=VALUEN
     ENDCASE
     SELECT (VAREA)
     LOCATE FOR &(VALUEC)
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="EOFP"
     SELECT (VAREA)
     VVALUE=EOF()
     SELECT 1
     IF VVALUE
         REPLACE VALUEC WITH "T"
     ELSE
         REPLACE VALUEC WITH "F"
     ENDIF
     REPLACE DONE WITH "T"
     COMMIT
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="RECNO"
     SELECT (VAREA)
     VVALUE=RECNO()
     SELECT 1
     REPLACE VALUEN WITH VVALUE
     REPLACE DONE WITH "T"
     COMMIT
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="RECCOUNT"
     SELECT (VAREA)
     VVALUE=RECCOUNT()
     SELECT 1
     REPLACE VALUEN WITH VVALUE
     REPLACE DONE WITH "T"
     COMMIT
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="SKIP"
     SELECT (VAREA)
     SKIP
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="CREATE"
     DO CASE
         CASE REFLINE=0
             VTABLENAME=TRIM(NAME)
             CAMPOSSTRUCT := {}
         CASE REFLINE>0
             AADD(CAMPOSSTRUCT, { VALUEC , VALUEC2 , INT(VALUEN) , INT(VALUEN2) } )
             IF NROLINNEXT=0
                 DBCREATE( (TABLA1) , CAMPOSSTRUCT )
             ENDIF
     ENDCASE
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="GETFIELDS"
CASE DDLDML="CONTROL" .AND. OP="SLEEP"
     VPAUSERES=SLEEP(VALUEN)
CASE DDLDML="CON" .AND. OP="CONCAT" .AND. REFBY=0
     PVARNAME=NAME
     PRIVATE &PVARNAME
     &PVARNAME=""
CASE DDLDML="CON" .AND. OP="CONCAT" .AND. REFBY > 0
     IF VALUEN>0
          &PVARNAME=&PVARNAME+SUBSTR(VALUEC,1,VALUEN)
     ELSE
          &PVARNAME=&PVARNAME+VALUEC
     ENDIF
CASE DDLDML="CON" .AND. OP="QUIT"
     CANCEL
OTHERWISE
     REPLACE VALUEC WITH "ERROR, EL COMANDO NO EXISTE."
ENDCASE
SELECT 1
REFBY = NROLINNEXT
REFBYNROLIN = NROLIN
DO WHILE RECNO() = LASTREC()
  PAUSERES=SLEEP( 0.5 )
ENDDO
PASO++
GO (PASO)
ENDDO
