/*
EJEMPLOS
~/compile_farm/woody/var/farmas/fuentes/dbfapi CREARDRIVER driv001
~/compile_farm/woody/var/farmas/fuentes/dbfapi CARGARDRIVER driv001 3 4 5 CREATE
~/compile_farm/woody/var/farmas/fuentes/dbfapi CARGARDRIVER driv001 DDLDML C DDL GO 1
~/compile_farm/woody/var/farmas/fuentes/dbfapi CARGARDRIVER driv001 ENTITY C TABLE GO 1
*/
DO GX_INIT
PARA TABLA0, TABLA1, PNAME3, PTYPE4, PVALUE5, PCREATE6, PGO7, PGORN8
PRIVATE TERMINAR
TERMINAR=.F.
WHILE .NOT. TERMINAR .AND. .NOT. EOF()
DO CASE
CASE TABLA0="CREARDRIVER"
     SELECT 1
     PRIVATE CAMPOSSTRUCT
     CAMPOSSTRUCT := {}
     AADD(CAMPOSSTRUCT, { "DDLDML" , "C" , 3 , 0 } )
     AADD(CAMPOSSTRUCT, { "ENTITY" , "C" , 15 , 0 } )
     AADD(CAMPOSSTRUCT, { "OP" , "C" , 15 , 0 } )
     AADD(CAMPOSSTRUCT, { "NAME" , "C" , 15 , 0 } )
     AADD(CAMPOSSTRUCT, { "TYPE" , "C" , 15 , 0 } )
     AADD(CAMPOSSTRUCT, { "VALUEC" , "C" , 15 , 0 } )
     AADD(CAMPOSSTRUCT, { "VALUED" , "D" , 8 , 0 } )
     AADD(CAMPOSSTRUCT, { "VALUEN" , "N" , 18 , 5 } )
     DBCREATE( (TABLA1) , CAMPOSSTRUCT )
     TERMINAR=.T.

CASE TABLA0="CARGARDRIVER"
     SELECT 1
     USE &TABLA1
     DO CASE
     	CASE PCREATE6="CREATE"
	     APPEND BLANK
     	CASE PGO7="GO"
	     GO VAL(PGORN8)
     	CASE PTYPE4="C"
	     REPLACE &PNAME3 WITH PVALUE5
     	CASE PTYPE4="N"
	     REPLACE &PNAME3 WITH VAL(PVALUE5)
     ENDCASE
     TERMINAR=.T.

CASE DDLDML="DML" .AND. ENTITY="FIELD" .AND. OP="C"
     SELECT 2
     APPEND BLANK
     REPLACE &NOMBRE WITH VALOR
CASE DDLDML="DML" .AND. ENTITY="FIELD" .AND. OP="R"
CASE DDLDML="DML" .AND. ENTITY="FIELD" .AND. OP="U"
CASE DDLDML="DML" .AND. ENTITY="FIELD" .AND. OP="D"
CASE DDLDML="DDL" .AND. ENTITY="INDEX" .AND. OP="SET"
CASE DDLDML="DDL" .AND. ENTITY="INDEX" .AND. OP="CREATE"
CASE DDLDML="DDL" .AND. ENTITY="INDEX" .AND. OP="REINDEX"
CASE DDLDML="DDL" .AND. ENTITY="INDEX" .AND. OP="DELETE"
CASE DDLDML="DDL" .AND. ENTITY="ORDER" .AND. OP="SET"
CASE DDLDML="DDL" .AND. ENTITY="ORDER" .AND. OP="UNSET"
CASE DDLDML="DDL" .AND. ENTITY="ORDER" .AND. OP="GET"
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="USE"
     SELECT 1
     VTABLA=NOMBRE
    
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="GO"
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="SEEK"
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="SEARCH"
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="SKIP"
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="CREATE"
CASE DDLDML="DDL" .AND. ENTITY="TABLE" .AND. OP="GETFIELDS"


ENDCASE

ENDDO
